Controllers/DateForLessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ekipage.Data;
using ekipage.Models;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Authorization;

namespace ekipage.Controllers
{
    public class DateForLessonController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DateForLessonController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DateForLesson
        public async Task<IActionResult> Index()
        {

            var hest = _context.Rider
                .FromSqlRaw("SELECT * FROM Rider") //INNER JOIN Horse ON Rider.HorseId = Horse.HorseId")
                .ToList();

            ViewBag.text = hest;
            
            /*
            var hest = (from h in _context.Horse
                        select h).ToList();

            ViewBag.text = hest;
            */

            /*
            IQueryable<Horse> Hest =
                from hejhej in _context.Horse select hejhej;

            ViewBag.text = Hest.ToList();
            */

            var applicationDbContext = _context.DateForLesson.Include(d => d.LessonContent);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DateForLesson/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dateForLesson = await _context.DateForLesson
                .Include(d => d.LessonContent)
                .FirstOrDefaultAsync(m => m.DateForLessonId == id);
            if (dateForLesson == null)
            {
                return NotFound();
            }

            return View(dateForLesson);
        }

        // GET: DateForLesson/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["LessonContentId"] = new SelectList(_context.LessonContent, "LessonContentId", "Lesson");
            return View();
        }

        // POST: DateForLesson/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateForLessonId,Date,LessonContentId")] DateForLesson dateForLesson)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dateForLesson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonContentId"] = new SelectList(_context.LessonContent, "LessonContentId", "Lesson", dateForLesson.LessonContentId);
            return View(dateForLesson);
        }

        // GET: DateForLesson/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dateForLesson = await _context.DateForLesson.FindAsync(id);
            if (dateForLesson == null)
            {
                return NotFound();
            }
            ViewData["LessonContentId"] = new SelectList(_context.LessonContent, "LessonContentId", "Lesson", dateForLesson.LessonContentId);
            return View(dateForLesson);
        }

        // POST: DateForLesson/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("DateForLessonId,Date,LessonContentId")] DateForLesson dateForLesson)
        {
            if (id != dateForLesson.DateForLessonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dateForLesson);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DateForLessonExists(dateForLesson.DateForLessonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonContentId"] = new SelectList(_context.LessonContent, "LessonContentId", "Lesson", dateForLesson.LessonContentId);
            return View(dateForLesson);
        }

        // GET: DateForLesson/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dateForLesson = await _context.DateForLesson
                .Include(d => d.LessonContent)
                .FirstOrDefaultAsync(m => m.DateForLessonId == id);
            if (dateForLesson == null)
            {
                return NotFound();
            }

            return View(dateForLesson);
        }

        // POST: DateForLesson/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dateForLesson = await _context.DateForLesson.FindAsync(id);
            _context.DateForLesson.Remove(dateForLesson);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DateForLessonExists(int id)
        {
            return _context.DateForLesson.Any(e => e.DateForLessonId == id);
        }
    }
}

Controllers/HorseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ekipage.Data;
using ekipage.Models;
using Microsoft.AspNetCore.Authorization;

namespace ekipage.Controllers
{
    public class HorseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HorseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Horse
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Horse.ToListAsync());
        }

        // GET: Horse/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horse = await _context.Horse
                .FirstOrDefaultAsync(m => m.HorseId == id);
            if (horse == null)
            {
                return NotFound();
            }

            return View(horse);
        }

        // GET: Horse/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Horse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("HorseId,HorseName,HorseTemper,HorseDescription")] Horse horse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horse);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(horse);
        }

        // GET: Horse/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horse = await _context.Horse.FindAsync(id);
            if (horse == null)
            {
                return NotFound();
            }
            return View(horse);
        }

        // POST: Horse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("HorseId,HorseName,HorseTemper,HorseDescription")] Horse horse)
        {
            if (id != horse.HorseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HorseExists(horse.HorseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(horse);
        }

        // GET: Horse/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horse = await _context.Horse
                .FirstOrDefaultAsync(m => m.HorseId == id);
            if (horse == null)
            {
                return NotFound();
            }

            return View(horse);
        }

        // POST: Horse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var horse = await _context.Horse.FindAsync(id);
            _context.Horse.Remove(horse);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HorseExists(int id)
        {
            return _context.Horse.Any(e => e.HorseId == id);
        }
    }
}

Controllers/RiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ekipage.Data;
using ekipage.Models;
using Microsoft.AspNetCore.Authorization;

namespace ekipage.Controllers
{
    public class RiderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RiderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rider
        public async Task<IActionResult> Index()
        {
            var validDate = _context.DateForLesson
                .FromSqlRaw("SELECT * FROM DateForLesson")
                .ToList();

            ViewBag.dateInfo = validDate;

            var applicationDbContext = _context.Rider.Include(r => r.Horse);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rider/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rider = await _context.Rider
                .Include(r => r.Horse)
                .FirstOrDefaultAsync(m => m.RiderId == id);
            if (rider == null)
            {
                return NotFound();
            }

            return View(rider);
        }

        // GET: Rider/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["HorseId"] = new SelectList(_context.Horse, "HorseId", "HorseName");
            return View();
        }

        // POST: Rider/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("RiderId,RiderName,Preference,HorseId")] Rider rider)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseId"] = new SelectList(_context.Horse, "HorseId", "HorseName", rider.HorseId);
            return View(rider);
        }

        // GET: Rider/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rider = await _context.Rider.FindAsync(id);
            if (rider == null)
            {
                return NotFound();
            }
            ViewData["HorseId"] = new SelectList(_context.Horse, "HorseId", "HorseName", rider.HorseId);
            return View(rider);
        }

        // POST: Rider/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("RiderId,RiderName,Preference,HorseId")] Rider rider)
        {
            if (id != rider.RiderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RiderExists(rider.RiderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseId"] = new SelectList(_context.Horse, "HorseId", "HorseName", rider.HorseId);
            return View(rider);
        }

        // GET: Rider/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rider = await _context.Rider
                .Include(r => r.Horse)
                .FirstOrDefaultAsync(m => m.RiderId == id);
            if (rider == null)
            {
                return NotFound();
            }

            return View(rider);
        }

        // POST: Rider/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rider = await _context.Rider.FindAsync(id);
            _context.Rider.Remove(rider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RiderExists(int id)
        {
            return _context.Rider.Any(e => e.RiderId == id);
        }
    }
}

Views/Shared/_CafePartial.cshtml
<div class="cafePartial">
    <div class="text-center">
        <div class="alignText">
            <p class="font-weight-bold">Ryttarcaféets öppettider:</p>
            Vardagar 16-20<br />
            Helger 10-15<br />
            Välkomna!
            </div>
        </div>
    </div>

Views/Shared/_DayAndDatePartial.cshtml
@model IEnumerable<ekipage.Models.DateForLesson>

<div class="testLektionstyp">
    <div class="text-center">

        <h2>###Datum###</h2>
        <p>Måndag 18:00</p>
        <p>@Html.DisplayNameFor(model => model.LessonContent): ###lektionstyp###</p>

    </div>
</div>

<!--
FUNKAR INTE :/
(nullvärde)

Amodel ekipage.Models.DateForLesson
    <div class="testLektionstyp">
        <h2>Testutskrift</h2>
        <p>
            Datum: AModel.Date <br />
            Lektionstyp: AModel.LessonContent
        </p>
    </div>

***

(nullvärde)
Amodel IEnumerable<ekipage.Models.LessonContent>
Aforeach (var item in Model)
    {
        AHtml.DisplayFor(modelItem => item.Lesson)
    }

-->

Views/Shared/_HorseAndRiderPartial.cshtml
@model IEnumerable<ekipage.Models.Rider>

    <div class="dagensGrupp">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.RiderName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Horse)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <!--
    <tbody>
        Aforeach (var item in Model)
        {
            <tr>
                <td>
                    AHtml.DisplayFor(modelItem => item.RiderName)
                </td>
                <td>
                    AHtml.DisplayFor(modelItem => item.Horse.HorseName)
                </td>
            </tr>
        }
    </tbody>
        -->
        </table>

    </div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ekipage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Rider" asp-action="Index">ekipage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" 
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <!--
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
            </li>
                -->

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rider" asp-action="Index">Elever</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DateForLesson" asp-action="Index">Datum</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-muted" asp-area="" asp-controller="Horse" asp-action="Index">Hästar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-muted" asp-area="" asp-controller="LessonContent" asp-action="Index">Lektionstyp</a>
                            </li>

                        </ul>
                    }
                    </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ekipage <!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>